Repository rafaelandrade/save4me, pull requests merged in 2022-03, with the labels that each got.

#14 [FEAT] adding prisma schema
  backend/prisma/schema.prisma
Labels: review

#8 [FEAT] Adding input component
  .github/workflows/bump.yml
  .github/workflows/codecov.yml
  .github/workflows/deploy.yml
  .vscode/settings.json
  frontend/.babelrc
  frontend/.eslintrc.json
  frontend/__tests__/sum.test.js
  frontend/components/input/index.js
  frontend/components/input/styles.jsx
  frontend/cypress/integration/index.spec.js
  frontend/jest.config.js
  frontend/package.json
  frontend/pages/_app.js
  frontend/pages/_document.js
  frontend/pages/index.js
  frontend/public/icons/Plus.jsx
  frontend/public/icons/Search.jsx
  frontend/styles/Home.module.css
  frontend/styles/globals.css
  frontend/styles/home.jsx
  yarn.lock
Labels: enhancement, review

#19 [FEAT] Adding tags and linkbutton
  frontend/components/input/index.js
  frontend/components/input/styles.jsx
  frontend/components/linkButton/index.js
  frontend/components/linkButton/styles.jsx
  frontend/components/tags/index.js
  frontend/components/tags/styles.jsx
  frontend/pages/index.js
  frontend/public/icons/Close.jsx
  frontend/public/icons/Plus.jsx
  frontend/styles/home.jsx
Labels: enhancement, review

#18 [FEAT] Adding loading global
  backend/package.json
  frontend/components/loading/index.js
  frontend/components/loading/styles.jsx
  frontend/public/icons/LoadingPoint.jsx
  package.json
Labels: enhancement, review

#9 [FEAT] Adding scrapper service
  backend/__tests__/unit/services/scrapper.test.js
  backend/package.json
  backend/src/services/index.js
  backend/src/services/scrapper/index.js
  yarn.lock
Labels: enhancement, WIP

#15 Feat: adding endpoint to save link
  .github/workflows/codecov.yml
  backend/.eslintrc.js
  backend/__tests__/Dockerfile.mongo
  backend/__tests__/docker-compose.test.yml
  backend/__tests__/run-tests.sh
  backend/__tests__/unit/controllers/healthController.test.js
  backend/__tests__/unit/controllers/saveLinks.test.js
  backend/__tests__/unit/helpers/generateRandomId.test.js
  backend/__tests__/unit/services/saveForMeService/create.test.js
  backend/__tests__/unit/services/saveForMeService/remove.test.js
  backend/__tests__/unit/services/saveForMeService/saveForMeService.test.js
  backend/__tests__/unit/services/saveForMeService/update.test.js
  backend/jest.config.js
  backend/jest.setup.js
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/constants/index.js
  backend/src/constants/saveForMeServiceConstants.js
  backend/src/controllers/healthController/index.js
  backend/src/controllers/index.js
  backend/src/controllers/saveForMeController/index.js
  backend/src/controllers/saveForMeController/saveLinks/index.js
  backend/src/helpers/generateRandomId.js
  backend/src/helpers/index.js
  backend/src/routes/v1/index.js
  backend/src/routes/v1/saveforme/index.js
  backend/src/services/index.js
  backend/src/services/saveForMeService/create.js
  backend/src/services/saveForMeService/index.js
  backend/src/services/saveForMeService/remove.js
  backend/src/services/saveForMeService/update.js
  yarn.lock
Labels: enhancement, review

#22 Fix: Avoid deepsource verification on frontend
  .deepsource.toml
Labels: review

#20 [FEAT] Adding design
  .github/workflows/bump.yml
  .github/workflows/deploy.yml
  .vscode/settings.json
  Procfile
  backend/__tests__/unit/helpers/generateRandomId.test.js
  backend/__tests__/unit/services/saveForMeService/create.test.js
  backend/__tests__/unit/services/saveForMeService/remove.test.js
  backend/__tests__/unit/services/saveForMeService/update.test.js
  backend/src/helpers/generateRandomId.js
  backend/src/helpers/index.js
  backend/src/routes/v1/saveforme/index.js
  backend/src/services/saveForMeService/create.js
  backend/src/services/saveForMeService/index.js
  backend/src/services/saveForMeService/remove.js
  backend/src/services/saveForMeService/update.js
  frontend/.gitignore
  frontend/README.md
  frontend/build-inject.js
  frontend/components/button/index.js
  frontend/components/input/index.js
  frontend/components/input/styles.jsx
  frontend/components/linkButton/index.js
  frontend/components/list/index.js
  frontend/components/list/link.js
  frontend/components/list/styles.jsx
  frontend/components/tags/index.js
  frontend/components/tags/styles.jsx
  frontend/cypress/fixtures/saveforme.json
  frontend/cypress/integration/index.spec.js
  frontend/cypress/support/commands.js
  frontend/next.config.wizardcopy.js
  frontend/package.json
  frontend/pages/_error.js
  frontend/pages/index.js
  frontend/pages/login.js
  frontend/pages/newLink.js
  frontend/public/background.js
  frontend/public/icons/ArrowLeft.jsx
  frontend/public/icons/Edit.jsx
  frontend/public/icons/Help.jsx
  frontend/public/icons/SearchNotFound.jsx
  frontend/public/icons/Trash.jsx
  frontend/public/inject.js
  frontend/public/manifest.json
  frontend/public/plugin/128x128.png
  frontend/public/plugin/16x16.png
  frontend/public/plugin/48x48.png
  frontend/sentry.client.config.js
  frontend/sentry.properties
  frontend/sentry.server.config.js
  frontend/services/api.js
  frontend/services/sentry.js
  frontend/styles/home.jsx
  package.json
  yarn.lock
Labels: WIP
